import Head from 'next/head'
import { useRouter } from 'next/router'
import Profile from '@/components/user-profile/Profile'
//import ABI from '@/components/abi/ABI'
//import Contract from '@/components/contract/contract'
//import { connectToContract } from '@/components/wallet/MetamaskSmartContract'

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute flex flex-col items-center justify-center w-full">
        <div>
          <h2>
            {' '}
            <Profile />
          </h2>
        </div>
      </div>
    </>
  )
}
